### ISSUE TITLE
tool: `elz fmt` shouldn't remove comment

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/elz#247]
To reproduce, run `elz fmt .` at the project root, and would find `lib/prelude/prelude.elz` be reformatted.

Another important thing was we would not like to remove the newline for two elements, e.g.

```elz
class k {}

foo(): void {}
```

should be kept, but we would like to remove newlines to 1 newline, e.g.

```elz
class k {}


foo(): void {}
```

should be

```elz
class k {}

foo(): void {}
```

**Comment by dannypsnl** [comment]
Some missing details:
1. comment could be related to top-level elements like: `class`, `trait`, `function`, `variable`, and class members `method`, `static method`, `field`
2. comment should keep indent with the level, e.g.

    ```
    if true {
    // comment
      foo();
    }
    ```

    should be

    ```
    if true {
      // comment
      foo();
    }
    ```

**Comment by YanHerChen** [comment]
Insert comment/blank concept into ast.
- [ ] Describe comment in ast.
- [ ] Handle comment in parser.

**Comment by YanHerChen** [comment]
### Describe comment in ast
```
pub struct Comment {
    pub location: Location,
    pub name: String,
    pub typ: ParsedType,
}
```

**Comment by dannypsnl** [comment]
Why a comment would have name and type as fields?

**Comment by dannypsnl** [comment]
You only handle comments at top-level. How about comments in function body? Comments in class definition between members?

**Comment by YanHerChen** [comment]
### Formatter Scheme
The initial idea is to read the entire code, mainly use `{` `}` `;` `//` to break lines. 
If blank> 1, remove them all, just give a blank, e.g.

`x:　　int　=　1　　　　　;`

should be

`x: int = 1;`

and

If no blank, need to add 1 blank e.q.

`x:int=1;`

should be

`x: int = 1;`



An example about new line , e.q.

`foo():void{x:int=1;}`

should be

```
foo(): void {
  x: int = 1;
}
```

**Comment by YanHerChen** [comment]
About Symbol:
1. The symbol `:` need to add a blank in the next space.
2. The symbol `+ - * / = ` need to add blank in the previous space and next space.
3. The symbol `;` need to add a blank in the previous space.

About comment, formatter  reserve `\n` to distinguish the end position of comment, e.q.

```
//This is comment line
x
    :
     int
      =
       1
       ;
```

in formatter

```
//This is comment line \n
x \n
    : \n
     int \n
      = \n
       1 \n
       ; \n
```

formatter reserve `\n` in comment line and `;` , it should be:

```
//This is comment line
x: int = 1;\n
```

**Comment by dannypsnl** [comment]
@YanHerChen can the formatter emits the correct newline on different platforms? For example, Windows uses `\r\n` and Unix-like uses `\n`.

**Comment by YanHerChen** [comment]
@dannypsnl Maybe the formatter need to handle `\r\n` and `\n`, but I will try `\n` on Windows first.

**Comment by dannypsnl** [comment]
> @dannypsnl Maybe the formatter need to handle `\r\n` and `\n`, but I will try `\n` on Windows first.

I believe we cannot do that, it might break the assumption of files in Window of some programs.
