### ISSUE TITLE
The character is not yet implemented.

### ISSUE THREAD

**Issue by YanHerChen** [dannypsnl/elz#280]
The character `#` is not yet implemented in src\lexer\mod.rs:331:17

**Comment by dannypsnl** [comment]
What's your input code and how to reproduce it? # is not yet implemented looks correctly for me.

**Comment by YanHerChen** [comment]
@dannypsnl I only test  `#[test]`.

`#` should be ignore?

**Comment by dannypsnl** [comment]
> @dannypsnl I only test `#[test]`.
> 
> `#` should be ignore?

It's an invalid input in case. We probably would use it in the future but that's not the point here.

**Comment by dannypsnl** [comment]
And notice that `#[test]` is Rust syntax, in elz has `@tag` for a similar purpose

**Comment by YanHerChen** [comment]
@dannypsnl Thank you for your description
